### ISSUE TITLE
Not a function exception 

### ISSUE THREAD

**Issue by liorfr** [jkroso/parse-duration#18]
Import with
import parse from "parse-duration";
or
import {parse} from "parse-duration";

use it:
parse("10s")

you will get
"parse_duration_1.default is not a function"

Can you please provide a type script example of how to use parse-duration?

Thanks,
Lior

**Comment by dy** [comment]
https://codesandbox.io/s/hungry-robinson-lwnb5?file=/src/index.js

**Comment by liorfr** [comment]
Please see TS project:
https://codesandbox.io/s/misty-framework-1u19b?file=/src/index.ts

It can be solved by adding
"esModuleInterop": true
To the tsconfig.json but a namespace solution is a bad practice


Thanks
Lior
